age=int(input('How old are you?:'))
#print(f'On your next birthday you will be + {age + 1}')
#egg=int(input('How many egg cartons do you have?:'))
#print(f'You have  + {egg*12} eggs.')
#cookies=int(input('How many cookies do you have?:'))
#people=int(input('How many people are there?:'))
#print(f'Each person gets {people/cookies} cookies')